# Define service name and configuration (定义服务名称和配置)
services:
  # Define a service using Vite4, Vue3, and Nginx (定义一个使用 Vite4, Vue3 和 Nginx 的服务)
  vite4_vue3_nginx:
    # Build Docker image (构建 Docker 镜像)
    build: .
    # Set the container name (设置容器名称)
    container_name: vite4_vue3_nginx
    # Map the container's port 80 to the host's port 8000 (将容器的 80 端口映射到主机的 8000 端口)
    ports:
      - 8000:80
  # Define a Vite4 and Vue3 Express backend service (定义一个使用 Vite4 和 Vue3 的 Express 后端服务)
  vite4_vue3_backend:
    # Build Docker image (构建 Docker 镜像)
    build: ./examples/express-demo
    # Set the container name (设置容器名称)
    container_name: vite4_vue3_backend
    # Run the npm start command to start the service (运行 npm start 命令来启动服务)
    command: npm start
